import { describe, it, expect } from "vitest";
import { readFileSync, existsSync, unlinkSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { PELAUT_DIR } from "../src/config.js";

/**
 * These tests call the real generateCaddyfile() which writes to ~/.pelaut/Caddyfile.
 * We read the file after generation to verify contents.
 * Note: The test uses the real store (empty by default) and real process-manager
 * (no running ports), so we're testing the "no servers" and "stopped servers" cases.
 */

describe("caddy – Caddyfile generation", () => {
    const CADDYFILE = join(PELAUT_DIR, "Caddyfile");

    it("generates a valid Caddyfile with dashboard block", async () => {
        const { generateCaddyfile } = await import("../src/caddy.js");
        generateCaddyfile();

        expect(existsSync(CADDYFILE)).toBe(true);
        const content = readFileSync(CADDYFILE, "utf-8");

        // Should contain the local_certs directive
        expect(content).toContain("local_certs");
        // Should contain the dashboard reverse proxy
        expect(content).toContain("localhost:2000");
        expect(content).toContain("reverse_proxy 127.0.0.1:2001");
        // Should contain the admin endpoint
        expect(content).toContain("admin localhost:2019");
    });

    it("includes entries for registered servers (stopped)", async () => {
        const store = await import("../src/store.js");
        const { generateCaddyfile } = await import("../src/caddy.js");

        // Add a test server
        store.add({ name: "caddy-test-srv", cmd: "echo hi", cwd: "/tmp" });

        try {
            generateCaddyfile();
            const content = readFileSync(CADDYFILE, "utf-8");

            // Should contain the server's .localhost domain
            expect(content).toContain("caddy-test-srv.localhost");
            // Since it's not running, should respond with 503
            expect(content).toContain("503");
        } finally {
            store.remove("caddy-test-srv");
        }
    });

    it("auto-generated header is present", async () => {
        const { generateCaddyfile } = await import("../src/caddy.js");
        generateCaddyfile();

        const content = readFileSync(CADDYFILE, "utf-8");
        expect(content).toContain("Auto-generated by pelaut");
    });
});

describe("caddy – binary detection", () => {
    it("ensureCaddy is an async function", async () => {
        const { ensureCaddy } = await import("../src/caddy.js");
        expect(typeof ensureCaddy).toBe("function");
        // Returns a promise
        const result = ensureCaddy();
        expect(result).toBeInstanceOf(Promise);
    });
});
